version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    # Example Traefik labels (disabled by default). Uncomment and adjust if you use Traefik.
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.time-tracker.rule=Host(`your.domain.tld`)"
    #   - "traefik.http.routers.time-tracker.entrypoints=websecure"
    #   - "traefik.http.routers.time-tracker.tls=true"
    #   - "traefik.http.services.time-tracker.loadbalancer.server.port=80"
